word_list = [
    "python", "github", "developer", "keyboard", "science", "elephant",
    "football", "banana", "computer", "internet", "monitor", "laptop",
    "charger", "printer", "speaker", "headphone", "microphone", "browser",
    "website", "network", "database", "programming", "function", "variable",
    "integer", "string", "boolean", "condition", "iteration", "looping",
    "compile", "execute", "terminal", "console", "software", "hardware",
    "algorithm", "debugging", "framework", "library", "package", "virtual",
    "machine", "storage", "memory", "process", "thread", "backend",
    "frontend", "desktop", "mobile", "android", "windows", "linux",
    "ubuntu", "server", "client", "router", "switch", "modem",
    "security", "firewall", "encryption", "decryption", "password", "username",
    "profile", "dashboard", "calendar", "attendance", "quotation", "kanban",
    "project", "manager", "student", "teacher", "college", "hostel",
    "library", "notebook", "pencil", "eraser", "marker", "backpack",
    "uniform", "lecture", "semester", "subject", "physics", "chemistry",
    "biology", "mathematics", "geometry", "algebra", "history", "geography",
    "economics", "language", "english", "tamil", "hindi", "french",
    "spanish", "italian", "german", "korean", "japanese", "chinese",
    "drawing", "painting", "singing", "dancing", "acting", "writing",
    "reading", "gaming", "streaming", "editing", "designing", "animation",
    "camera", "photography", "sunlight", "rainfall", "thunder", "lightning",
    "mountain", "river", "ocean", "waterfall", "island", "village",
    "highway", "airport", "station", "railway", "journey", "traveler",
    "tourism", "holiday", "festival", "birthday", "wedding", "friendship",
    "brother", "sister", "mother", "father", "family", "cousin",
    "uncle", "aunty", "grandfather", "grandmother", "happiness", "sadness",
    "kindness", "bravery", "honesty", "freedom", "success", "failure",
    "motivation", "discipline", "confidence", "patience", "exercise", "workout",
    "fitness", "running", "walking", "cycling", "swimming", "cricket",
    "volleyball", "basketball", "badminton", "tennis", "hockey", "kabaddi",
    "wrestling", "captain", "stadium", "tournament", "victory", "defeat",
    "breakfast", "lunch", "dinner", "chapathi", "biryani", "sandwich",
    "pancake", "chocolate", "vanilla", "strawberry", "pineapple", "watermelon",
    "cucumber", "tomato", "potato", "carrot", "spinach", "onion",
    "garlic", "ginger", "pepper", "turmeric", "cinnamon", "cardamom",
    "coffee", "milkshake", "lemonade", "smoothie", "restaurant", "kitchen",
    "bedroom", "bathroom", "balcony", "curtain", "wardrobe", "television",
    "refrigerator", "washing", "airplane", "helicopter", "bicycle", "scooter",
    "traffic", "petrol", "diesel", "battery", "engine", "factory",
    "hospital", "medicine", "vitamin", "doctor", "nurse", "patient",
    "fever", "cough", "allergy", "healthy", "disease", "sunrise",
    "sunset", "midnight", "morning", "evening", "weekend", "monday",
    "tuesday", "wednesday", "thursday", "friday", "saturday", "january",
    "february", "march", "april", "august", "september", "october",
    "november", "december", "diamond", "emerald", "sapphire", "treasure",
    "kingdom", "warrior", "soldier", "pirates", "dragon", "monster",
    "unicorn", "phoenix", "wizard", "castle", "adventure", "mystery",
    "fantasy", "galaxy", "planet", "satellite", "rocket", "astronaut",
    "universe", "gravity", "energy", "magnet", "voltage", "current",
    "circuit", "robotics", "artificial", "intelligence", "machinelearning",
    "datascience", "blockchain", "cryptocurrency", "startup", "innovation",
    "leadership", "communication", "teamwork", "creativity", "strategy",
    "research", "analysis", "solution", "challenge", "opportunity",
    "achievement"
]